apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-project
  template:
    metadata:
      labels:
        app: ns-project
    spec:
      containers:
        - name: ns-project
          image: starmansn/ns-project:latest
          ports:
            - containerPort: 9371