spring.application.name=myservice

server.port=9371

bootstrap.servers=185.154.52.222:9092

#spring.kafka.properties.advertised.host.name=185.154.52.222
#spring.kafka.properties.advertised.port=9092


ssh serviceman@185.154.52.218 -p 12333

scp -P 12333 C:\Users\nimae\IdeaProjects\myservice\build\libs\myservice.jar serviceman@185.154.52.218:/home