#spring.kafka.listener.auto-startup=true
spring.kafka.bootstrap-servers: 185.154.52.222:9092
spring.kafka.consumer.group-id= stub-group
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.max-poll-records: 50
spring.kafka.topic=test_topic

spring.datasource.url=jdbc:postgresql://185.154.52.218:5432/n_project
spring.datasource.username=postgres
spring.datasource.password=I5vV!W=xyM77T,SwbO_I.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9371

spring.application.name=NS-project
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
instance.url=10.56.170.48:9371
url.vm=http://31.76.225.70:8428/api/v1/import/prometheus

app.kafka.delay-ms=1000
